name: example
description: A new Flutter project.
version: 0.9.0
homepage: https://github.com/iktakahiro/dart_iso_calendar
repository: https://github.com/iktakahiro/dart_iso_calendar

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  iso_calendar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
